// element-plus-version/src/components/library/IndicatorCard.vue
<script setup lang="ts">
import { TrendingUp, FileText, Calendar } from 'lucide-vue-next'
import type { LucideIcon } from 'lucide-vue-next'

export interface IndicatorData {
  id: string
  name: string
  dimension: string
  ruleType: string
  ruleDesc: string
  ruleCode: string
  mapField: string
  period: string
}

const props = defineProps<{
  data: IndicatorData
}>()

defineEmits<{
  (e: 'click'): void
}>()

const getDimensionIcon = (dim: string): LucideIcon => {
  switch (dim) {
    case '销售业绩': return TrendingUp
    case '产品力': return FileText
    default: return Calendar
  }
}
</script>

<template>
  <el-card 
    shadow="hover" 
    class="custom-el-card group cursor-pointer"
    @click="$emit('click')"
  >
    <div class="flex flex-col h-full">
      <div class="flex items-start justify-between mb-4">
        <div class="p-2 bg-indigo-50 rounded-xl text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white transition-all duration-300">
          <component :is="getDimensionIcon(props.data.dimension)" class="h-5 w-5" />
        </div>
        <el-tag size="small" effect="plain" round class="indicator-badge">
          {{ props.data.dimension }}
        </el-tag>
      </div>

      <h3 class="font-black text-slate-900 leading-tight mb-2 group-hover:text-indigo-600 transition-colors">
        {{ props.data.name }}
      </h3>
      
      <p class="text-[10px] text-slate-400 font-bold mb-4 line-clamp-2 italic">
        {{ props.data.ruleDesc }}
      </p>

      <div class="mt-auto pt-4 border-t border-slate-50 flex items-center justify-between">
        <div class="flex items-center gap-1.5">
          <div class="w-1.5 h-1.5 rounded-full bg-emerald-500"></div>
          <span class="text-[9px] font-black text-slate-500 uppercase tracking-widest">{{ props.data.ruleType }}</span>
        </div>
        <span class="text-[9px] font-black text-slate-300 uppercase tracking-widest">{{ props.data.period === 'month' ? '月度' : '年度' }}</span>
      </div>
    </div>
  </el-card>
</template>

<style scoped>
:deep(.custom-el-card) {
  border-radius: 24px !important;
  border-color: #f1f5f9 !important;
  transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
  height: 100%;
}
:deep(.custom-el-card:hover) {
  transform: translateY(-4px);
  border-color: #e0e7ff !important;
  box-shadow: 0 20px 25px -5px rgba(79, 70, 229, 0.1) !important;
}

:deep(.custom-el-card .el-card__body) {
  height: 100%;
  padding: 1.5rem !important;
  transition: background-color 0.3s;
}

:deep(.custom-el-card:hover .el-card__body) {
  background-color: #f1f5f9;
}

:deep(.custom-el-card .indicator-badge) {
  font-size: 10px !important;
  font-weight: 900 !important;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  background-color: #4f46e5 !important;
  color: white !important;
  border: none !important;
}
</style>

// src/components/library/IndicatorCard.tsx
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Settings2, TrendingUp, Package, Users, Activity, BarChart3, Clock, Wallet } from "lucide-react";

interface IndicatorData {
    id: string;
    name: string;
    dimension: string;
    ruleType: string;
    ruleDesc: string;
}

const getDimensionIcon = (dimension: string) => {
    switch (dimension) {
        case '销售业绩': return <TrendingUp className="w-3 h-3 mr-1" />;
        case '产品力': return <Package className="w-3 h-3 mr-1" />;
        case '市场指标': return <Activity className="w-3 h-3 mr-1" />;
        case '渠道力': return <BarChart3 className="w-3 h-3 mr-1" />;
        case '费用管理': return <Wallet className="w-3 h-3 mr-1" />;
        case '组织力': return <Users className="w-3 h-3 mr-1" />;
        case '行动计划': return <Clock className="w-3 h-3 mr-1" />;
        default: return <Settings2 className="w-3 h-3 mr-1" />;
    }
};

const getDimensionColor = (dimension: string) => {
    switch (dimension) {
        case '销售业绩': return 'bg-red-50 text-red-600 border-red-100 hover:bg-red-100';
        case '产品力': return 'bg-orange-50 text-orange-600 border-orange-100 hover:bg-orange-100';
        case '市场指标': return 'bg-blue-50 text-blue-600 border-blue-100 hover:bg-blue-100';
        case '渠道力': return 'bg-indigo-50 text-indigo-600 border-indigo-100 hover:bg-indigo-100';
        case '费用管理': return 'bg-emerald-50 text-emerald-600 border-emerald-100 hover:bg-emerald-100';
        case '组织力': return 'bg-purple-50 text-purple-600 border-purple-100 hover:bg-purple-100';
        case '行动计划': return 'bg-cyan-50 text-cyan-600 border-cyan-100 hover:bg-cyan-100';
        default: return 'bg-slate-50 text-slate-600 border-slate-100 hover:bg-slate-100';
    }
}

export function IndicatorCard({ data, onClick }: { data: IndicatorData; onClick: () => void }) {
    return (
        <Card
            className="group relative cursor-pointer hover:shadow-lg hover:-translate-y-0.5 transition-all duration-300 border-slate-200 hover:border-blue-300 overflow-hidden"
            onClick={onClick}
        >
            <div className="absolute top-0 left-0 w-1 h-full bg-slate-200 group-hover:bg-blue-500 transition-colors duration-300"></div>
            <CardHeader className="pb-1 px-3 pt-3 flex flex-col items-start gap-1.5">
                <Badge variant="outline" className={`font-normal px-2 py-0 text-[10px] ${getDimensionColor(data.dimension)}`}>
                    {getDimensionIcon(data.dimension)}
                    {data.dimension}
                </Badge>
                <CardTitle className="text-sm font-semibold text-slate-800 leading-snug group-hover:text-blue-600 transition-colors line-clamp-2" title={data.name}>
                    {data.name}
                </CardTitle>
            </CardHeader>
            <CardContent className="px-3 pb-3">
                <div className="flex items-center gap-1.5 mb-1">
                    <Settings2 className="h-3 w-3 text-slate-400 shrink-0" />
                    <span className="text-xs font-medium text-slate-600 truncate">{data.ruleType}</span>
                </div>
                <p className="text-[11px] text-slate-500 italic leading-snug line-clamp-2" title={data.ruleDesc}>
                    {data.ruleDesc}
                </p>
            </CardContent>
        </Card>
    );
}
